title: <p>Anshuman Acharya</p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/anshuman-acharya-868a9227/">LinkedIn</a> |
  <a href="https://github.com/anshuman-acharya">GitHub</a>
  <p align="left">
  <br>   
  Working on Data Science, AI, Machine learning & NLP related problems.
  Working with Oracle Financial Services Software at Keybank OBP Product functional team.
  Worked with Infosys at Core Banking functional team.
  <br>
  </p>



theme: jekyll-theme-minimal
